name: continuous-integration

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: install go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.1
      
      - name: run tests
        run: go test -v ./...
        
      - name: run linting
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

      - name: pull request title validator [default]
        uses: ./ # kontrolplane/pull-request-title-validator@latest
